### ISSUE TITLE
How to sign out after sign-in

### ISSUE THREAD

**Issue by viratsoft** [maxgfr/android-youtube-api#1]
Hello,
 Not sign out function.
how to sign out?

**Comment by maxgfr** [comment]
Hi vihatsoft, 

I've not implemented this feature yet. 

It could be interesting to do that. If you want some informations about it, here is the link of the official doc Google OAUTH2 authentification : https://developers.google.com/identity/protocols/oauth2

Someone who has got the same issue : https://stackoverflow.com/questions/12909332/how-to-logout-of-an-application-where-i-used-oauth2-to-login-with-google

**Comment by maxgfr** [comment]
Disclaimer :

To be clear, this project is just a sample application. 

I created it just to test Youtube API quickly. It is not a complete version of the processus of OAUTH2 authenfication
